version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  valute_converter:
    build:
      context: ./valute_converter
    container_name: valute_converter
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TOPIC_REQUESTS: currency_requests
      TOPIC_RESPONSES: currency_responses
    ports:
      - "5000:5000"

  transaction_manager:
    build:
      context: ./transaction_manager_service
    container_name: transaction_manager
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      CONSUMER_TOPIC: transaction_topic
      PRODUCER_TOPIC: process_transaction

  transaction_service:
    build:
      context: ./transaction_service
    container_name: transaction_service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      CONSUMER_TOPIC: process_transaction

  notification_service:
    build:
      context: ./notification_service
    container_name: notification_service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      NOTIFICATION_TOPIC: notification_topic
